services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","no","--requirepass","${REDIS_PASSWORD}"]
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" PING | grep PONG"]
      interval: 5s
      timeout: 2s
      retries: 10



volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge