volumes:
  redis-throttler-data:
    driver: local

networks:
  app-network:
    driver: bridge


services:
  redis-throttler:
    image: redis:7-alpine
    container_name: redis-throttler
    command:
      [
        'redis-server',
        '--appendonly',
        'no',
        '--requirepass',
        '${REDIS_THROTTLER_PASSWORD}',
      ]
    ports:
      - '127.0.0.1:${REDIS_THROTTLER_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_THROTTLER_PASSWORD}
    volumes:
      - redis-throttler-data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a "$${REDIS_THROTTLER_PASSWORD}" PING | grep PONG']
      interval: 5s
      timeout: 2s
      retries: 10